name: flutter_accessory_manager_example
description: "Demonstrates how to use the flutter_accessory_manager plugin."
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_accessory_manager:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
